language: cpp
sudo: required
matrix:
    include:
    - os: osx
      compiler: clang
      osx_image: xcode10.3
      script:
      - bash scripts/build.macos.release.sh
      deploy:
        provider: releases
        api_key: "$GITHUB_OAUTH_TOKEN"
        file: "stairspeedtest_reborn_darwin64.tar.gz"
        skip_cleanup: true
        draft: true
        on:
          tags: true
    - services: docker
      script:
      - docker pull alpine:latest
      - docker run -v $TRAVIS_BUILD_DIR:/root/workdir -e TRAVIS_BRANCH -e TRAVIS_TAG alpine:latest /bin/sh -c "apk add bash git && cd /root/workdir && bash scripts/build.alpine.release.sh"
      deploy:
        provider: releases
        api_key: "$GITHUB_OAUTH_TOKEN"
        file: "stairspeedtest_reborn_linux64.tar.gz"
        skip_cleanup: true
        draft: true
        on:
          tags: true
